# https://graspingtech.com/ansible-nginx-static-site/
---
- hosts: ubunvm
  become: yes
  tasks: 
  - name: "create www directory"
    file:
      path: /usr/share/nginx/html/{{ domain_name }}
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: upload nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/conf.d/{{ domain_name }}.conf
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx
  - name: upload index.html
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/{{ domain_name }}/index.html
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted